

<?php
//fichier temporaire à canger avec le temps en base de donnée 
$cartes = array(
  array(
    'type_page' => 'HTML',
    'title_page' => 'HTML',
    'description' => 'Langage de balisage utilisé pour la création de pages web, permettant notamment de définir des liens hypertextes.',
  ),
  array(
    'type_page' => 'CSS',
    'title_page' => 'CSS',
    'description' => 'Langage de feuilles de styles en cascade, servant à mettre en forme des documents web, type page HTML ou XML',
  ),
  array(
    'type_page' => 'WP',
    'title_page' => 'WORDPRESS',
    'description' => 'WordPress est un logiciel très populaire qui est utilisé sur le web pour créer un site ou un blog.',
  ),
  array(
    'type_page' => 'PS',
    'title_page' => 'PHOTOSHOP',
    'description' => 'Photoshop est un logiciel de retouche, de traitement et de dessin assisté par ordinateur.',
  ),
  array(
    'type_page' => 'IA',
    'title_page' => 'ILLUSTRATOR',
    'description' => 'Adobe Illustrator est un logiciel de création graphique vectorielle.',
  ),
  array(
    'type_page' => 'PHP',
    'title_page' => 'PHP',
    'description' => 'Un langage de programmation libre, principalement utilisé pour produire des pages Web dynamiques via un serveur HTTP.',
  )
);

$carousel = array(
  array(
    'auteur' => 'Auteur',
    'date' => 'date',
    'type' => 'HTML',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'Auteur',
    'date' => 'Date',
    'type' => 'HTML',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'Auteur',
    'date' => 'Date',
    'type' => 'HTML',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurCSS',
    'date' => 'dateCSS',
    'type' => 'CSS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurCSS',
    'date' => 'DateCSS',
    'type' => 'CSS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurCSS',
    'date' => 'DateCSS',
    'type' => 'CSS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurWP',
    'date' => 'dateWP',
    'type' => 'WP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurWP',
    'date' => 'DateWP',
    'type' => 'WP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurWP',
    'date' => 'DateWP',
    'type' => 'WP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPS',
    'date' => 'datePS',
    'type' => 'PS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPS',
    'date' => 'DatePS',
    'type' => 'PS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPS',
    'date' => 'DatePS',
    'type' => 'PS',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurIA',
    'date' => 'dateIA',
    'type' => 'IA',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurIA',
    'date' => 'DateIA',
    'type' => 'IA',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurIA',
    'date' => 'DateIA',
    'type' => 'IA',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPHP',
    'date' => 'datePHP',
    'type' => 'PHP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPHP',
    'date' => 'DatePHP',
    'type' => 'PHP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  ),
  array(
    'auteur' => 'AuteurPHP',
    'date' => 'DatePHP',
    'type' => 'PHP',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa?',
  )
);


$cards = array(
  array(
    'id' => '1',
    'type' => 'HTML',
    'title' => 'Le titre',
    'auteur' => 'L\'auteur',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '2',
    'type' => 'HTML',
    'title' => 'Le titre2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '3',
    'type' => 'HTML',
    'title' => 'Le titre3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '4',
    'type' => 'HTML',
    'title' => 'Le titre4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '5',
    'type' => 'CSS',
    'title' => 'Le titrecss',
    'auteur' => 'L\'auteurcss',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '6',
    'type' => 'CSS',
    'title' => 'Le titrecss2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '7',
    'type' => 'CSS',
    'title' => 'Le titreccss3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '8',
    'type' => 'CSS',
    'title' => 'Le titrecss4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '9',
    'type' => 'IA',
    'title' => 'Le titreIA',
    'auteur' => 'L\'auteurIA',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '10',
    'type' => 'IA',
    'title' => 'Le titreIA2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '11',
    'type' => 'IA',
    'title' => 'Le titrecIA3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '12',
    'type' => 'IA',
    'title' => 'Le titreIA4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '13',
    'type' => 'PHP',
    'title' => 'Le titrePHP',
    'auteur' => 'L\'auteurPHP',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '14',
    'type' => 'PHP',
    'title' => 'Le titrePHP2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '15',
    'type' => 'PHP',
    'title' => 'Le titrecPHP3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '16',
    'type' => 'PHP',
    'title' => 'Le titrePHP4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ), 
  array(
    'id' => '17',
    'type' => 'PS',
    'title' => 'Le titrePS',
    'auteur' => 'L\'auteurPS',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '18',
    'type' => 'PS',
    'title' => 'Le titrePS2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '19',
    'type' => 'PS',
    'title' => 'Le titrecPS3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '20',
    'type' => 'PS',
    'title' => 'Le titrePS4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '21',
    'type' => 'WP',
    'title' => 'Le titreWP',
    'auteur' => 'L\'auteurWP',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '22',
    'type' => 'WP',
    'title' => 'Le titreWP2',
    'auteur' => 'L\'auteur2',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '23',
    'type' => 'WP',
    'title' => 'Le titrecWP3',
    'auteur' => 'L\'auteur3',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  ),
  array(
    'id' => '24',
    'type' => 'WP',
    'title' => 'Le titreWP4',
    'auteur' => 'L\'auteur4',
    'avatar' => 'https://www.renault.fr/etc/designs/renault_v2/19.10.2.RENAULT-1882/common-assets/img/avatar/avatar.png',
    'date' => 'Date',
    'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex magnam voluptatibus dolor dolorum. Corrupti dicta illo omnis cumque atque totam sed iusto eos quod sapiente enim quisquam, exercitationem molestiae ipsa...',
  )
);

?>